[default]
EXTENSIONS = [
    'settings.env:init_app',
    'settings.extensions:init_app',
    'settings.management.mail:init_app'
    'settings.management.apis:init_app'
    'settings.management.caching:init_app'
]
